
const PROPTY_DATA = {
  properties: [
    {
      id: 'p001',
      title: '3 Bed Apartment · Gulshan 2',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
      price: 85000,
      priceType: 'rent',
      area: 1850,
      bedrooms: 3,
      bathrooms: 3,
      floor: 8,
      totalFloors: 12,
      type: 'Apartment',
      furnishing: 'Semi-Furnished',
      facing: 'South',
      parking: true,
      location: { area: 'Gulshan 2', thana: 'Gulshan', city: 'Dhaka' },
      badge: 'Gold',
      agentId: 'a001',
      colors: ['#4F46E5', '#6366F1'],
      description: 'Spacious 3-bedroom apartment in the heart of Gulshan 2. Floor-to-ceiling windows with panoramic city views. Building amenities include a gym, rooftop garden, and round-the-clock security.',
      pricePerSqft: 46,
      views: 342,
      postedDays: 3,
      amenities: ['Gym', 'Generator', 'Lift', 'Security', 'Car Parking', 'Rooftop Garden'],
      lat: 23.792, lng: 90.414,
    },
    {
      id: 'p002',
      title: '4 Bed Duplex · Banani',
      image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
      price: 130000,
      priceType: 'rent',
      area: 3200,
      bedrooms: 4,
      bathrooms: 4,
      floor: 5,
      totalFloors: 6,
      type: 'Duplex',
      furnishing: 'Furnished',
      facing: 'North',
      parking: true,
      location: { area: 'Banani', thana: 'Banani', city: 'Dhaka' },
      badge: 'Gold',
      agentId: 'a002',
      colors: ['#0891B2', '#06B6D4'],
      description: 'Rare duplex apartment in prime Banani location. Features a private terrace, designer kitchen, and Italian marble flooring. Perfect for executive families.',
      pricePerSqft: 41,
      views: 511,
      postedDays: 7,
      amenities: ['Private Terrace', 'Generator', 'Lift', 'Swimming Pool', 'Car Parking', 'Concierge'],
      lat: 23.794, lng: 90.404,
    },
    {
      id: 'p003',
      title: '2 Bed Apartment · Dhanmondi',
      image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80',
      price: 42000,
      priceType: 'rent',
      area: 1200,
      bedrooms: 2,
      bathrooms: 2,
      floor: 4,
      totalFloors: 8,
      type: 'Apartment',
      furnishing: 'Unfurnished',
      facing: 'East',
      parking: false,
      location: { area: 'Dhanmondi', thana: 'Dhanmondi', city: 'Dhaka' },
      badge: 'Silver',
      agentId: 'a003',
      colors: ['#059669', '#10B981'],
      description: 'Well-maintained 2-bedroom apartment in peaceful Dhanmondi. Close to schools, hospitals, and Rabindra Sarobar lake. Ideal for small families.',
      pricePerSqft: 35,
      views: 189,
      postedDays: 12,
      amenities: ['Generator', 'Lift', 'Security', 'Rooftop'],
      lat: 23.747, lng: 90.374,
    },
    {
      id: 'p004',
      title: '5 Bed Villa · Baridhara',
      image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80',
      price: 38500000,
      priceType: 'sale',
      area: 5800,
      bedrooms: 5,
      bathrooms: 6,
      floor: 1,
      totalFloors: 3,
      type: 'House',
      furnishing: 'Semi-Furnished',
      facing: 'West',
      parking: true,
      location: { area: 'Baridhara', thana: 'Baridhara', city: 'Dhaka' },
      badge: 'Gold',
      agentId: 'a001',
      colors: ['#7C3AED', '#8B5CF6'],
      description: 'Magnificent 5-bedroom independent villa in prestigious Baridhara. Triple-height entrance foyer, private garden, and staff quarters. Rare opportunity in diplomatic zone.',
      pricePerSqft: 6638,
      views: 892,
      postedDays: 1,
      amenities: ['Private Garden', 'Swimming Pool', 'Home Theatre', 'Staff Quarters', 'Multi-car Garage', 'Security Room'],
      lat: 23.797, lng: 90.424,
    },
    {
      id: 'p005',
      title: '3 Bed Apartment · Mirpur DOHS',
      image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80',
      price: 55000,
      priceType: 'rent',
      area: 1650,
      bedrooms: 3,
      bathrooms: 3,
      floor: 6,
      totalFloors: 10,
      type: 'Apartment',
      furnishing: 'Semi-Furnished',
      facing: 'South',
      parking: true,
      location: { area: 'Mirpur DOHS', thana: 'Mirpur', city: 'Dhaka' },
      badge: 'Gold',
      agentId: 'a002',
      colors: ['#D97706', '#F59E0B'],
      description: 'Premium apartment in the secured Mirpur DOHS community. Quiet environment with parks, schools, and club facilities within walking distance.',
      pricePerSqft: 33,
      views: 267,
      postedDays: 5,
      amenities: ['Club House', 'Generator', 'Lift', 'Security', 'Car Parking', 'Park View'],
      lat: 23.821, lng: 90.368,
    },
    {
      id: 'p006',
      title: '2 Bed Apartment · Uttara Sector 7',
      image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
      price: 32000,
      priceType: 'rent',
      area: 1100,
      bedrooms: 2,
      bathrooms: 2,
      floor: 3,
      totalFloors: 7,
      type: 'Apartment',
      furnishing: 'Unfurnished',
      facing: 'North',
      parking: false,
      location: { area: 'Uttara', thana: 'Uttara', city: 'Dhaka' },
      badge: 'Silver',
      agentId: 'a003',
      colors: ['#BE185D', '#EC4899'],
      description: 'Affordable and well-connected apartment in Uttara Sector 7. Close to Hazrat Shahjalal International Airport and the upcoming Metro Rail station.',
      pricePerSqft: 29,
      views: 143,
      postedDays: 18,
      amenities: ['Generator', 'Lift', 'Security'],
      lat: 23.868, lng: 90.398,
    },
    {
      id: 'p007',
      title: '3 Bed Apartment · Bashundhara R/A',
      image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
      price: 65000,
      priceType: 'rent',
      area: 1950,
      bedrooms: 3,
      bathrooms: 3,
      floor: 9,
      totalFloors: 14,
      type: 'Apartment',
      furnishing: 'Furnished',
      facing: 'East',
      parking: true,
      location: { area: 'Bashundhara', thana: 'Bashundhara', city: 'Dhaka' },
      badge: 'Gold',
      agentId: 'a004',
      colors: ['#0F766E', '#14B8A6'],
      description: 'Fully furnished high-rise apartment with stunning views from the 9th floor. Modern kitchen appliances, smart home features, and premium finishes throughout.',
      pricePerSqft: 33,
      views: 421,
      postedDays: 2,
      amenities: ['Gym', 'Generator', 'Lift', 'Security', 'Car Parking', 'Smart Home'],
      lat: 23.815, lng: 90.427,
    },
    {
      id: 'p008',
      title: '1 Bed Studio · Mohakhali',
      image: 'https://images.unsplash.com/photo-1536376074432-8d642fed43f7?auto=format&fit=crop&w=800&q=80',
      price: 28000,
      priceType: 'rent',
      area: 750,
      bedrooms: 1,
      bathrooms: 1,
      floor: 2,
      totalFloors: 5,
      type: 'Studio',
      furnishing: 'Furnished',
      facing: 'West',
      parking: false,
      location: { area: 'Mohakhali', thana: 'Mohakhali', city: 'Dhaka' },
      badge: 'Silver',
      agentId: 'a004',
      colors: ['#1D4ED8', '#3B82F6'],
      description: 'Compact fully-furnished studio perfect for young professionals. Minutes from Mohakhali bus terminal and multiple corporate offices.',
      pricePerSqft: 37,
      views: 98,
      postedDays: 22,
      amenities: ['Generator', 'Lift', 'Security'],
      lat: 23.779, lng: 90.400,
    },
  ],

  agents: [
    {
      id: 'a001',
      name: 'Rahim Uddin Chowdhury',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
      initials: 'RC',
      title: 'Senior Property Consultant',
      areas: ['Gulshan', 'Baridhara', 'Banani', 'Niketan'],
      experience: 9,
      verified: true,
      rating: 4.9,
      reviewCount: 87,
      deals: 214,
      responseTime: '< 30 min',
      languages: ['Bangla', 'English'],
      phone: '+880 1711-XXXXXX',
      bio: 'Specializing in premium properties across Gulshan and Baridhara for over 9 years. Former REHAB board member. Ranked #1 agent on Propty for Q1 2025.',
      listingIds: ['p001', 'p004'],
    },
    {
      id: 'a002',
      name: 'Fatema Khanam',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
      initials: 'FK',
      title: 'Residential Specialist',
      areas: ['Banani', 'Mirpur DOHS', 'Cantonment'],
      experience: 6,
      verified: true,
      rating: 4.8,
      reviewCount: 62,
      deals: 145,
      responseTime: '< 1 hr',
      languages: ['Bangla', 'English', 'Hindi'],
      phone: '+880 1812-XXXXXX',
      bio: 'Expert in DOHS and military housing areas. Helps military families and corporates find quality homes with full legal transparency.',
      listingIds: ['p002', 'p005'],
    },
    {
      id: 'a003',
      name: 'Arif Hossain',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
      initials: 'AH',
      title: 'Leasing Consultant',
      areas: ['Dhanmondi', 'Uttara', 'Mohammadpur'],
      experience: 4,
      verified: true,
      rating: 4.6,
      reviewCount: 38,
      deals: 89,
      responseTime: '< 2 hr',
      languages: ['Bangla', 'English'],
      phone: '+880 1611-XXXXXX',
      bio: 'Young and tech-savvy consultant specializing in mid-market rentals. Uses data to help buyers make smart decisions.',
      listingIds: ['p003', 'p006'],
    },
    {
      id: 'a004',
      name: 'Nadia Rahman',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
      initials: 'NR',
      title: 'Investment Property Advisor',
      areas: ['Bashundhara', 'Mohakhali', 'Badda'],
      experience: 7,
      verified: true,
      rating: 4.7,
      reviewCount: 54,
      deals: 172,
      responseTime: '< 1 hr',
      languages: ['Bangla', 'English'],
      phone: '+880 1911-XXXXXX',
      bio: 'Focuses on investment-grade properties and rental yield optimization. Advises NRBs on Bangladesh real estate from abroad.',
      listingIds: ['p007', 'p008'],
    },
  ],

  reviews: [
    { agentId: 'a001', reviewer: 'Tamal Ahmed', rating: 5, date: 'March 2025', text: 'Rahim bhai found us the perfect apartment in Gulshan within a week. His knowledge of the area is unmatched.', deal: 'Rented 3BHK in Gulshan 2' },
    { agentId: 'a001', reviewer: 'Priya Sharma', rating: 5, date: 'February 2025', text: 'Extremely professional and transparent. No hidden fees, no surprises. Highly recommended for premium properties.', deal: 'Purchased villa in Baridhara' },
    { agentId: 'a002', reviewer: 'Brig. (Retd.) Karim', rating: 5, date: 'March 2025', text: 'Fatema understands the DOHS system perfectly. Made our relocation completely stress-free.', deal: 'Rented in Mirpur DOHS' },
    { agentId: 'a003', reviewer: 'Mehjabin Chowdhury', rating: 4, date: 'January 2025', text: 'Very helpful and responsive. Got good value for my Dhanmondi apartment.', deal: 'Rented 2BHK in Dhanmondi' },
    { agentId: 'a004', reviewer: 'Sabbir NRB', rating: 5, date: 'February 2025', text: 'Nadia handled everything while I was in London. Signed the agreement remotely, totally seamless.', deal: 'Investment apartment in Bashundhara' },
  ],

  areas: [
    { name: 'Gulshan', count: 234, avgRent: 72000, x: 68, y: 44 },
    { name: 'Banani', count: 187, avgRent: 65000, x: 58, y: 48 },
    { name: 'Baridhara', count: 98, avgRent: 95000, x: 76, y: 40 },
    { name: 'Dhanmondi', count: 312, avgRent: 45000, x: 38, y: 62 },
    { name: 'Mirpur', count: 445, avgRent: 38000, x: 28, y: 32 },
    { name: 'Uttara', count: 389, avgRent: 32000, x: 52, y: 14 },
    { name: 'Bashundhara', count: 276, avgRent: 55000, x: 82, y: 30 },
    { name: 'Mohakhali', count: 156, avgRent: 35000, x: 55, y: 52 },
  ],
};
